/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
	int y;
};
typedef struct operandos operandos;

#define SOMA_SUB_PROG 123
#define SOMA_SUB_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA 1
extern  int * soma_1(operandos *, CLIENT *);
extern  int * soma_1_svc(operandos *, struct svc_req *);
#define SUBTRACAO 2
extern  int * subtracao_1(operandos *, CLIENT *);
extern  int * subtracao_1_svc(operandos *, struct svc_req *);
extern int soma_sub_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define SUBTRACAO 2
extern  int * subtracao_1();
extern  int * subtracao_1_svc();
extern int soma_sub_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
