/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATORIAL_H_RPCGEN
#define _FATORIAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operando {
	int x;
};
typedef struct operando operando;

#define FATORIAL_PROG 1234
#define FATORIAL_VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA 1
extern  int * soma_2(operando *, CLIENT *);
extern  int * soma_2_svc(operando *, struct svc_req *);
extern int fatorial_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA 1
extern  int * soma_2();
extern  int * soma_2_svc();
extern int fatorial_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operando (XDR *, operando*);

#else /* K&R C */
extern bool_t xdr_operando ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FATORIAL_H_RPCGEN */
