
/**
* FileInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* Terça-feira, 24 de Novembro de 2020 16h29min48s GFT
*/

public interface FileInterface extends FileInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileInterface
