
/**
* FileInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* Ter�a-feira, 24 de Novembro de 2020 16h14min48s GFT
*/

public abstract class FileInterfacePOA extends org.omg.PortableServer.Servant
 implements FileInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("downloadFile", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileInterface/downloadFile
       {
         String fileName = in.read_string ();
         byte $result[] = null;
         $result = this.downloadFile (fileName);
         out = $rh.createReply();
         FileInterfacePackage.DataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileInterface _this() 
  {
    return FileInterfaceHelper.narrow(
    super._this_object());
  }

  public FileInterface _this(org.omg.CORBA.ORB orb) 
  {
    return FileInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class FileInterfacePOA
